version: '3.9'
services:
  web:
    image: ubuntu:20.04
    build: .
    ports:
      - "8800:80"
    networks:
      box:
        ipv4_address:  172.100.1.3

networks:
  box:
    ipam:
      driver: default
      config:
        - subnet:  172.100.1.0/24
